build:
  version: "2.0"

accounts:
  message: "Welcome to EasyBank accounts related qa APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@easybank.com"
  onCallSupport:
    - (333) 555-1234
    - (333) 523-1345