build:
  version: "3.0"

loans:
  message: "Welcome to EasyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@easybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934