spring:
  application:
    name: "configserver"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: git
#    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/vamshi-23/MicroServices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "file:///Users/vamshi/Documents/IntelliJ/easybytes/MicroServices/SpringCloudConfig-EB/src/main/resources/config"
#          search-locations: "classpath:/config"

encrypt:
  key: "DE3R4T5Y6HGFY7U68I67564TERGFHNNGRFW45"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true